import { FormEvent, useEffect, useState } from 'react'
import { CalendarDays, Mail, ShieldCheck, Users } from 'lucide-react'
import type { AgentKind, AgentResponse, AgentStatus, OnOfficeStatus } from '../models/api'
import { createCrmPreview, createEmailDraft, getAgentStatus, getOnOfficeStatus, simulateAppointment } from '../services/api'

const definitions = { crm: { title: 'CRM-Agent', subtitle: 'onOffice-Änderungen sicher vorbereiten', icon: Users }, email: { title: 'E-Mail-Agent', subtitle: 'E-Mails ausschließlich als Entwurf erstellen', icon: Mail }, calendar: { title: 'Termin-Agent', subtitle: 'Termine ohne Kalenderänderung simulieren', icon: CalendarDays } }

export function AgentPage({ agent }: { agent: AgentKind }) {
  const [status, setStatus] = useState<AgentStatus>(); const [onoffice, setOnoffice] = useState<OnOfficeStatus>(); const [result, setResult] = useState<AgentResponse>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [target, setTarget] = useState('seller'); const [name, setName] = useState(''); const [purpose, setPurpose] = useState(''); const [date, setDate] = useState('2026-07-20T10:00')
  useEffect(() => { setResult(undefined); setError(''); getAgentStatus(agent).then(setStatus).catch(e => setError(e.message)); if (agent === 'crm') getOnOfficeStatus().then(setOnoffice).catch(e => setError(e.message)) }, [agent])
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setResult(undefined); try { if (agent === 'crm') setResult(await createCrmPreview({ contact_reference: name, target_group: target, note: purpose })); if (agent === 'email') setResult(await createEmailDraft({ recipient_name: name, target_group: target, purpose, facts: [] })); if (agent === 'calendar') setResult(await simulateAppointment({ attendee_name: name, purpose, preferred_start: new Date(date).toISOString(), duration_minutes: 30, timezone: 'Europe/Berlin' })) } catch (e) { setError(e instanceof Error ? e.message : 'Anfrage fehlgeschlagen.') } finally { setBusy(false) } }
  const definition = definitions[agent]; const Icon = definition.icon
  return <div className="page agent-page"><header className="page-header"><div><span className="eyebrow">Sichere Agenten · Phase 1</span><h1><Icon size={30} />{definition.title}</h1><p>{definition.subtitle}</p></div></header><section className="agent-safety"><ShieldCheck /><div><strong>Externe Aktionen sind deaktiviert</strong><p>Mock-/Simulationsmodus. Es werden keine CRM-Daten geändert, Nachrichten versendet oder Termine gebucht.</p></div></section><section className="agent-status-grid"><div><small>Anbieter</small><strong>{status?.provider ?? 'Wird geladen …'}</strong></div><div><small>Modus</small><strong>{status?.mode ?? '–'}</strong></div><div><small>Verbindung</small><strong>{status?.provider_connected ? 'Bestätigt' : 'Nicht verbunden'}</strong></div><div><small>Prompt</small><strong>{status?.prompt_version ?? '–'}</strong></div>{agent === 'crm' && <><div><small>Datenquelle</small><strong>{onoffice?.authenticated ? 'onOffice' : 'Simulation'}</strong></div><div><small>Zugriff</small><strong>Schreibgeschützt</strong></div><div><small>Letzte Verbindung</small><strong>{onoffice?.last_check ? new Date(onoffice.last_check).toLocaleString('de-DE') : 'Noch nicht geprüft'}</strong></div></>}</section><form className="agent-form" onSubmit={submit}><label>{agent === 'crm' ? 'Kontaktreferenz' : 'Name'}<input required minLength={2} value={name} onChange={e => setName(e.target.value)} placeholder="Nur Testdaten verwenden" /></label>{agent !== 'calendar' && <label>Zielgruppe<select value={target} onChange={e => setTarget(e.target.value)}><option value="seller">Verkäufer</option><option value="buyer">Käufer</option><option value="investor">Kapitalanlage</option></select></label>}<label>{agent === 'crm' ? 'Notizvorschlag' : agent === 'email' ? 'Anlass und Inhalt' : 'Terminanlass'}<textarea required minLength={3} value={purpose} onChange={e => setPurpose(e.target.value)} /></label>{agent === 'calendar' && <label>Bevorzugter Zeitpunkt<input type="datetime-local" required value={date} onChange={e => setDate(e.target.value)} /></label>}<button className="primary-button" disabled={busy}>{busy ? 'Wird erstellt …' : agent === 'crm' ? 'CRM-Vorschau erstellen' : agent === 'email' ? 'Entwurf erstellen' : 'Termin simulieren'}</button></form>{error && <div className="error-message">{error}</div>}{result && <section className="agent-result"><span className={`doc-badge ${result.external_action_executed ? 'bad' : 'ok'}`}>{result.status}</span><h2>{result.summary}</h2><pre>{JSON.stringify(result.output, null, 2)}</pre><p><strong>Freigabe:</strong> {result.approval.reason}</p><small>Vorgang {result.request_id}</small></section>}</div>
}
