import {useCallback,useEffect,useMemo,useState} from 'react'
import type {DashboardConversation,DashboardLead,DashboardOverview,DashboardStatistics,DashboardWorkflow} from '../models/api'
import {getDashboardConversation,getDashboardConversations,getDashboardLeads,getDashboardOverview,getDashboardStatistics,getDashboardWorkflows,getOnOfficeStatus,openDashboardEvents} from '../services/api'
import {AgentStatusPanel} from '../components/dashboard/AgentStatusPanel'; import {ConversationPanel} from '../components/dashboard/ConversationPanel'; import {DashboardFilters,type DashboardFilter} from '../components/dashboard/DashboardFilters'; import {KnowledgePanel} from '../components/dashboard/KnowledgePanel'; import {LeadPanel} from '../components/dashboard/LeadPanel'; import {NotificationPanel} from '../components/dashboard/NotificationPanel'; import {OverviewCards} from '../components/dashboard/OverviewCards'; import {StatisticsPanel} from '../components/dashboard/StatisticsPanel'; import {WorkflowPanel} from '../components/dashboard/WorkflowPanel'
const initial={search:'',status:'',date_from:'',date_to:''}
export function DashboardPage(){const [overview,setOverview]=useState<DashboardOverview|null>(null),[calls,setCalls]=useState<DashboardConversation[]>([]),[selected,setSelected]=useState<DashboardConversation|null>(null),[workflows,setWorkflows]=useState<DashboardWorkflow[]>([]),[leads,setLeads]=useState<DashboardLead[]>([]),[stats,setStats]=useState<DashboardStatistics|null>(null),[legacy,setLegacy]=useState<{status:string;configured:string}|null>(null),[filters,setFilters]=useState<DashboardFilter>(initial),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const query=useMemo(()=>{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));return p.size?`?${p}`:''},[filters])
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [o,c,w,l,s]=await Promise.all([getDashboardOverview(),getDashboardConversations(query),getDashboardWorkflows(query),getDashboardLeads(query),getDashboardStatistics(query)]);setOverview(o);setCalls(c);setWorkflows(w);setLeads(l);setStats(s)}catch(e){try{const old=await getOnOfficeStatus();setLegacy({status:!old.enabled?'Deaktiviert':old.authenticated?'Lesemodus verbunden':'Nicht erreichbar',configured:old.configured?'Konfiguriert':'Nicht konfiguriert'})}catch{setError(e instanceof Error?e.message:'Dashboard konnte nicht geladen werden.')}}finally{setLoading(false)}},[query])
 useEffect(()=>{void load()},[load]);useEffect(()=>{const source=openDashboardEvents(()=>void load());if(!source)return;source.onerror=()=>source.close();return()=>source.close()},[load]);const select=async(id:string)=>{try{setSelected(await getDashboardConversation(id))}catch(e){setError(e instanceof Error?e.message:'Gespräch nicht verfügbar.')}}
 return <div className="page operator-dashboard"><header className="page-header"><div><span className="eyebrow">AKZENTA IMMOBILIEN</span><h1>AI Operator Dashboard</h1><p>Lesender Leitstand für Gespräche, Leads, Workflows und Agenten.</p></div><button className="primary-button" onClick={()=>void load()} disabled={loading}>{loading?'Lädt …':'Aktualisieren'}</button></header><DashboardFilters value={filters} onChange={setFilters}/>{error&&<div className="error-message">{error}</div>}{legacy&&<section className="system-details"><h2>onOffice</h2><p>{legacy.status}</p><p>{legacy.configured}</p></section>}{loading&&!overview&&<div className="loading">Dashboard wird geladen …</div>}{overview&&stats&&<><OverviewCards data={overview}/><div className="operator-main"><ConversationPanel items={calls} selected={selected} onSelect={id=>void select(id)}/><WorkflowPanel items={workflows}/><AgentStatusPanel items={overview.agent_statuses}/><NotificationPanel items={overview.recent_events}/><LeadPanel items={leads}/><StatisticsPanel data={stats}/>{selected&&<KnowledgePanel items={selected.knowledge_sources||[]}/>}</div></>}</div>}
